version: '3.8'

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=test_db
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  redis:
    image: docker.io/bitnami/redis:7.0
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass test123
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/bitnami/redis/data
    env_file:
      - dev.env

  fast-api-app:
    image: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test123
      - POSTGRES_DB=test_db
      - POOL_SIZE=5
      - MAX_OVERFLOW=-1
      - POOL_PRE_PING=True
      - ECHO=False
      - POOL_RECYCLE_IN_SECONDS=3600
      - ECHO_POOL=False
      - POOL_RESET_ON_RETURN=rollback
      - POOL_TIMEOUT_IN_SECONDS=30
      - POOL=~class:`~sqlalchemy.pool.QueuePool`
      - REDIS_URL=redis
      - REDIS_MAX_CONNECTION=10